# Generated by Django 5.2.1 on 2025-05-24 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_customeuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
